apiVersion: v1
kind: ReplicationController
metadata:
  name: v2ray
spec:
  replicas: 1
  selector:
    app: v2ray
  template:
    metadata:
      name: v2ray
      labels:
        app: v2ray
    spec:
      containers:
      - name: v2ray
        image: zhu327/v2ray
        ports:
        - containerPort: 8080
          name: tcp
        - containerPort: 8080
          protocol: UDP
          name: udp
        env:
          - name: CONFIG_JSON
            value: '{"log": {"access": "none"}, "inbounds": [{"port": 8080, "protocol": "vless", "settings": {"decryption": "none", "clients": [{"id": "18ad2c9c-a88b-48e8-aa64-5dee0045c282"}]}, "streamSettings": {"network": "mkcp", "kcpSettings": {"uplinkCapacity": 5, "downlinkCapacity": 100, "congestion": true, "header": {"type": "utp"}}}}], "outbounds": [{"protocol": "freedom", "settings": {}}]}'
---
apiVersion: v1
kind: Service
metadata:
  name: v2ray-rc-svc
spec:
  selector:
    app: v2ray
  type: NodePort
  ports:
  - protocol: TCP
    name: tcp
    port: 8080
    nodePort: 30080
  - protocol: UDP
    name: udp
    port: 8080
    nodePort: 30080
